// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKWIcIZuSaMGN1JvGWc1G7en9PlWlZduU',
    appId: '1:427560280036:web:dd19aaefd8f3aeff8071f1',
    messagingSenderId: '427560280036',
    projectId: 'teenple-61eab',
    authDomain: 'teenple-61eab.firebaseapp.com',
    storageBucket: 'teenple-61eab.firebasestorage.app',
    measurementId: 'G-WB10FG5042',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjatYRfQzw7sG1mfUT4bJb9iQ85vFPvo',
    appId: '1:427560280036:android:aa6899fd88695b028071f1',
    messagingSenderId: '427560280036',
    projectId: 'teenple-61eab',
    storageBucket: 'teenple-61eab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKWIcIZuSaMGN1JvGWc1G7en9PlWlZduU',
    appId: '1:427560280036:web:9c59bf0fcafa681b8071f1',
    messagingSenderId: '427560280036',
    projectId: 'teenple-61eab',
    authDomain: 'teenple-61eab.firebaseapp.com',
    storageBucket: 'teenple-61eab.firebasestorage.app',
    measurementId: 'G-7B50ZXCBP1',
  );
}
